version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/express-app

permissions:
  - object: /home/ubuntu/express-app
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
